apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-demo-deployment
spec:
  selector:
    matchLabels:
      app: gen-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: gen-demo
    spec:
      containers:
      - name: gen-demo
        image: xiaoshenge/gin-demo
        ports:
        - containerPort: 9090